// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xiggygdbonjrpmscegvc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhpZ2d5Z2Rib25qcnBtc2NlZ3ZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwNTA0NzgsImV4cCI6MjA3MTYyNjQ3OH0.7pZH5wnEEP1j4lNemoR19BlJsF4iMTyxFxM9gpSKl-w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});